// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.12.4
// source: ohlc.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FeedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FeedRequest) Reset() {
	*x = FeedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ohlc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FeedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedRequest) ProtoMessage() {}

func (x *FeedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ohlc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedRequest.ProtoReflect.Descriptor instead.
func (*FeedRequest) Descriptor() ([]byte, []int) {
	return file_ohlc_proto_rawDescGZIP(), []int{0}
}

type FeedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FeedResponse) Reset() {
	*x = FeedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ohlc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FeedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedResponse) ProtoMessage() {}

func (x *FeedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ohlc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedResponse.ProtoReflect.Descriptor instead.
func (*FeedResponse) Descriptor() ([]byte, []int) {
	return file_ohlc_proto_rawDescGZIP(), []int{1}
}

type GetStockListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetStockListRequest) Reset() {
	*x = GetStockListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ohlc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStockListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockListRequest) ProtoMessage() {}

func (x *GetStockListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ohlc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockListRequest.ProtoReflect.Descriptor instead.
func (*GetStockListRequest) Descriptor() ([]byte, []int) {
	return file_ohlc_proto_rawDescGZIP(), []int{2}
}

type StockList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stock   string `protobuf:"bytes,1,opt,name=stock,proto3" json:"stock,omitempty"`
	DayDate string `protobuf:"bytes,2,opt,name=day_date,json=dayDate,proto3" json:"day_date,omitempty"`
}

func (x *StockList) Reset() {
	*x = StockList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ohlc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StockList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockList) ProtoMessage() {}

func (x *StockList) ProtoReflect() protoreflect.Message {
	mi := &file_ohlc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockList.ProtoReflect.Descriptor instead.
func (*StockList) Descriptor() ([]byte, []int) {
	return file_ohlc_proto_rawDescGZIP(), []int{3}
}

func (x *StockList) GetStock() string {
	if x != nil {
		return x.Stock
	}
	return ""
}

func (x *StockList) GetDayDate() string {
	if x != nil {
		return x.DayDate
	}
	return ""
}

type GetStockListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*StockList `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *GetStockListResponse) Reset() {
	*x = GetStockListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ohlc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStockListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockListResponse) ProtoMessage() {}

func (x *GetStockListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ohlc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockListResponse.ProtoReflect.Descriptor instead.
func (*GetStockListResponse) Descriptor() ([]byte, []int) {
	return file_ohlc_proto_rawDescGZIP(), []int{4}
}

func (x *GetStockListResponse) GetList() []*StockList {
	if x != nil {
		return x.List
	}
	return nil
}

type GetStockSummaryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stock   string `protobuf:"bytes,1,opt,name=stock,proto3" json:"stock,omitempty"`
	DayDate string `protobuf:"bytes,2,opt,name=day_date,json=dayDate,proto3" json:"day_date,omitempty"`
}

func (x *GetStockSummaryRequest) Reset() {
	*x = GetStockSummaryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ohlc_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStockSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockSummaryRequest) ProtoMessage() {}

func (x *GetStockSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ohlc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockSummaryRequest.ProtoReflect.Descriptor instead.
func (*GetStockSummaryRequest) Descriptor() ([]byte, []int) {
	return file_ohlc_proto_rawDescGZIP(), []int{5}
}

func (x *GetStockSummaryRequest) GetStock() string {
	if x != nil {
		return x.Stock
	}
	return ""
}

func (x *GetStockSummaryRequest) GetDayDate() string {
	if x != nil {
		return x.DayDate
	}
	return ""
}

type GetStockSummaryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PreviousPrice string `protobuf:"bytes,1,opt,name=previous_price,json=previousPrice,proto3" json:"previous_price,omitempty"`
	OpenPrice     string `protobuf:"bytes,2,opt,name=open_price,json=openPrice,proto3" json:"open_price,omitempty"`
	HighestPrice  string `protobuf:"bytes,3,opt,name=highest_price,json=highestPrice,proto3" json:"highest_price,omitempty"`
	LowestPrice   string `protobuf:"bytes,4,opt,name=lowest_price,json=lowestPrice,proto3" json:"lowest_price,omitempty"`
	ClosePrice    string `protobuf:"bytes,5,opt,name=close_price,json=closePrice,proto3" json:"close_price,omitempty"`
	AveragePrice  string `protobuf:"bytes,6,opt,name=average_price,json=averagePrice,proto3" json:"average_price,omitempty"`
	Volume        string `protobuf:"bytes,7,opt,name=volume,proto3" json:"volume,omitempty"`
	Value         string `protobuf:"bytes,8,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *GetStockSummaryResponse) Reset() {
	*x = GetStockSummaryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ohlc_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStockSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockSummaryResponse) ProtoMessage() {}

func (x *GetStockSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ohlc_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockSummaryResponse.ProtoReflect.Descriptor instead.
func (*GetStockSummaryResponse) Descriptor() ([]byte, []int) {
	return file_ohlc_proto_rawDescGZIP(), []int{6}
}

func (x *GetStockSummaryResponse) GetPreviousPrice() string {
	if x != nil {
		return x.PreviousPrice
	}
	return ""
}

func (x *GetStockSummaryResponse) GetOpenPrice() string {
	if x != nil {
		return x.OpenPrice
	}
	return ""
}

func (x *GetStockSummaryResponse) GetHighestPrice() string {
	if x != nil {
		return x.HighestPrice
	}
	return ""
}

func (x *GetStockSummaryResponse) GetLowestPrice() string {
	if x != nil {
		return x.LowestPrice
	}
	return ""
}

func (x *GetStockSummaryResponse) GetClosePrice() string {
	if x != nil {
		return x.ClosePrice
	}
	return ""
}

func (x *GetStockSummaryResponse) GetAveragePrice() string {
	if x != nil {
		return x.AveragePrice
	}
	return ""
}

func (x *GetStockSummaryResponse) GetVolume() string {
	if x != nil {
		return x.Volume
	}
	return ""
}

func (x *GetStockSummaryResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type GetFeederStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetFeederStatusRequest) Reset() {
	*x = GetFeederStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ohlc_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFeederStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeederStatusRequest) ProtoMessage() {}

func (x *GetFeederStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ohlc_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeederStatusRequest.ProtoReflect.Descriptor instead.
func (*GetFeederStatusRequest) Descriptor() ([]byte, []int) {
	return file_ohlc_proto_rawDescGZIP(), []int{7}
}

type GetFeederStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *GetFeederStatusResponse) Reset() {
	*x = GetFeederStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ohlc_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFeederStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeederStatusResponse) ProtoMessage() {}

func (x *GetFeederStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ohlc_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeederStatusResponse.ProtoReflect.Descriptor instead.
func (*GetFeederStatusResponse) Descriptor() ([]byte, []int) {
	return file_ohlc_proto_rawDescGZIP(), []int{8}
}

func (x *GetFeederStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_ohlc_proto protoreflect.FileDescriptor

var file_ohlc_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x6f, 0x68, 0x6c, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x0d, 0x0a, 0x0b, 0x46, 0x65,
	0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x0e, 0x0a, 0x0c, 0x46, 0x65, 0x65,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x15, 0x0a, 0x13, 0x47, 0x65, 0x74,
	0x53, 0x74, 0x6f, 0x63, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x3c, 0x0a, 0x09, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74,
	0x6f, 0x63, 0x6b, 0x12, 0x19, 0x0a, 0x08, 0x64, 0x61, 0x79, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x61, 0x79, 0x44, 0x61, 0x74, 0x65, 0x22, 0x36,
	0x0a, 0x14, 0x47, 0x65, 0x74, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x49, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x53, 0x74, 0x6f,
	0x63, 0x6b, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x12, 0x19, 0x0a, 0x08, 0x64, 0x61, 0x79, 0x5f, 0x64, 0x61,
	0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x61, 0x79, 0x44, 0x61, 0x74,
	0x65, 0x22, 0x9b, 0x02, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x53, 0x75,
	0x6d, 0x6d, 0x61, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a,
	0x0e, 0x70, 0x72, 0x65, 0x76, 0x69, 0x6f, 0x75, 0x73, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x70, 0x72, 0x65, 0x76, 0x69, 0x6f, 0x75, 0x73, 0x50,
	0x72, 0x69, 0x63, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6f, 0x70, 0x65, 0x6e, 0x5f, 0x70, 0x72, 0x69,
	0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6f, 0x70, 0x65, 0x6e, 0x50, 0x72,
	0x69, 0x63, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x68, 0x69, 0x67, 0x68, 0x65, 0x73, 0x74, 0x5f, 0x70,
	0x72, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x68, 0x69, 0x67, 0x68,
	0x65, 0x73, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x6c, 0x6f, 0x77, 0x65,
	0x73, 0x74, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x6c, 0x6f, 0x77, 0x65, 0x73, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x63,
	0x6c, 0x6f, 0x73, 0x65, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x23, 0x0a, 0x0d,
	0x61, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x61, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x50, 0x72, 0x69, 0x63,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22,
	0x18, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x46, 0x65, 0x65, 0x64, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x31, 0x0a, 0x17, 0x47, 0x65, 0x74,
	0x46, 0x65, 0x65, 0x64, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0xdc, 0x02, 0x0a,
	0x04, 0x4f, 0x48, 0x4c, 0x43, 0x12, 0x3d, 0x0a, 0x04, 0x46, 0x65, 0x65, 0x64, 0x12, 0x0c, 0x2e,
	0x46, 0x65, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x46, 0x65,
	0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x18, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x12, 0x3a, 0x01, 0x2a, 0x22, 0x0d, 0x2f, 0x76, 0x31, 0x2f, 0x66, 0x65, 0x65, 0x64, 0x2d,
	0x64, 0x61, 0x74, 0x61, 0x12, 0x53, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x53, 0x74, 0x6f, 0x63, 0x6b,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x14, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x47, 0x65, 0x74,
	0x53, 0x74, 0x6f, 0x63, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x16, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x10, 0x12, 0x0e, 0x2f, 0x76, 0x31, 0x2f, 0x73,
	0x74, 0x6f, 0x63, 0x6b, 0x2d, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x5f, 0x0a, 0x0f, 0x47, 0x65, 0x74,
	0x53, 0x74, 0x6f, 0x63, 0x6b, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x12, 0x17, 0x2e, 0x47,
	0x65, 0x74, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x6f, 0x63, 0x6b,
	0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x19, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x13, 0x12, 0x11, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x74, 0x6f,
	0x63, 0x6b, 0x2d, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x12, 0x5f, 0x0a, 0x0f, 0x47, 0x65,
	0x74, 0x46, 0x65, 0x65, 0x64, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x17, 0x2e,
	0x47, 0x65, 0x74, 0x46, 0x65, 0x65, 0x64, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x65, 0x65, 0x64,
	0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x19, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x13, 0x12, 0x11, 0x2f, 0x76, 0x31, 0x2f, 0x66, 0x65,
	0x65, 0x64, 0x65, 0x72, 0x2d, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x0a, 0x5a, 0x08, 0x73,
	0x74, 0x6f, 0x63, 0x6b, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ohlc_proto_rawDescOnce sync.Once
	file_ohlc_proto_rawDescData = file_ohlc_proto_rawDesc
)

func file_ohlc_proto_rawDescGZIP() []byte {
	file_ohlc_proto_rawDescOnce.Do(func() {
		file_ohlc_proto_rawDescData = protoimpl.X.CompressGZIP(file_ohlc_proto_rawDescData)
	})
	return file_ohlc_proto_rawDescData
}

var file_ohlc_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_ohlc_proto_goTypes = []interface{}{
	(*FeedRequest)(nil),             // 0: FeedRequest
	(*FeedResponse)(nil),            // 1: FeedResponse
	(*GetStockListRequest)(nil),     // 2: GetStockListRequest
	(*StockList)(nil),               // 3: StockList
	(*GetStockListResponse)(nil),    // 4: GetStockListResponse
	(*GetStockSummaryRequest)(nil),  // 5: GetStockSummaryRequest
	(*GetStockSummaryResponse)(nil), // 6: GetStockSummaryResponse
	(*GetFeederStatusRequest)(nil),  // 7: GetFeederStatusRequest
	(*GetFeederStatusResponse)(nil), // 8: GetFeederStatusResponse
}
var file_ohlc_proto_depIdxs = []int32{
	3, // 0: GetStockListResponse.list:type_name -> StockList
	0, // 1: OHLC.Feed:input_type -> FeedRequest
	2, // 2: OHLC.GetStockList:input_type -> GetStockListRequest
	5, // 3: OHLC.GetStockSummary:input_type -> GetStockSummaryRequest
	7, // 4: OHLC.GetFeederStatus:input_type -> GetFeederStatusRequest
	1, // 5: OHLC.Feed:output_type -> FeedResponse
	4, // 6: OHLC.GetStockList:output_type -> GetStockListResponse
	6, // 7: OHLC.GetStockSummary:output_type -> GetStockSummaryResponse
	8, // 8: OHLC.GetFeederStatus:output_type -> GetFeederStatusResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ohlc_proto_init() }
func file_ohlc_proto_init() {
	if File_ohlc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ohlc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FeedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ohlc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FeedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ohlc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStockListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ohlc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StockList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ohlc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStockListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ohlc_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStockSummaryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ohlc_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStockSummaryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ohlc_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFeederStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ohlc_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFeederStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ohlc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ohlc_proto_goTypes,
		DependencyIndexes: file_ohlc_proto_depIdxs,
		MessageInfos:      file_ohlc_proto_msgTypes,
	}.Build()
	File_ohlc_proto = out.File
	file_ohlc_proto_rawDesc = nil
	file_ohlc_proto_goTypes = nil
	file_ohlc_proto_depIdxs = nil
}
